FypProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

core/urls.py
from django import views
from django.urls import path
from core.views import index, residence_view, search_view, residence_detail_view, my_listings_view, filter_residence, profile_view

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("residences/", residence_view, name="residence"),
    path("profile/", profile_view, name="profile"),
    path("my_listing/", my_listings_view, name="my_listing"),
    path("residence/<str:Rid>", residence_detail_view, name="residence_detail"),

    # search
    path("search/", search_view, name="search"),

    path("filter-residences/", filter_residence, name="filter-residences"),

]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
]

core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import User
from ckeditor_uploader.fields import RichTextUploadingField

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (
    (1,  "★☆☆☆☆"),
    (2,  "★★☆☆☆"),
    (3,  "★★★☆☆"),
    (4,  "★★★★☆"),
    (5,  "★★★★★"),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=20,
                         prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Room")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title
    
class Tags(models.Model):
    pass

class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length=10, max_length=20,
                         prefix="ven", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Fyp Home")
    address = models.CharField(max_length=100, default="123 Main Street.")
    contact1 = models.CharField(max_length=100, default="+123 (456) 789")
    contact2 = models.CharField(max_length=100, default="+123 (456) 789")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    class Meta:
        verbose_name_plural = "Vendors"


    def __str__(self):
        return self.title
    

class Residence(models.Model):
    Rid = ShortUUIDField(unique=True, length=10,
                         max_length=20, alphabet="abcdefgh12345")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, related_name="category")
    vendor = models.ForeignKey(
        Vendor, on_delete=models.SET_NULL, null=True, related_name="Residence")
    title = models.CharField(max_length=100, default="FYP home")
    image = models.ImageField(
        upload_to=user_directory_path, default="Residence.jpg")
    description = RichTextUploadingField(null=True, blank=True, default="This is the Redidence")
    policies = RichTextUploadingField(null=True, blank=True, default="This is the Redidence")
    features = RichTextUploadingField(null=True, blank=True, default="This is the Redidence")
    facilities = RichTextUploadingField(null=True, blank=True, default="This is the Redidence")

    price = models.DecimalField(
        max_digits=99999999999999, decimal_places=2, default="000")
    old_price = models.DecimalField(
        max_digits=99999999999999, decimal_places=2, default="000")
    address = models.CharField(max_length=100, default="123 Main Street.")
    # specifications = models.TextField(null=True, blank=True)
    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)
    type = models.CharField(
        max_length=100, default="Not couple friendly", null=True, blank=True)

    Residence_status = models.CharField(
        choices=STATUS, max_length=10, default="in_review")
    
    
    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length=4, max_length=10,
                        prefix="sku", alphabet="1234567890")
    
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Residences"

    def Residence_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

    def get_precentage(self):
        new_price = (100 - (self.price / self.old_price) * 100)
        return new_price


class ResidenceImages(models.Model):
    images = models.ImageField(
        upload_to="Residence-images", default="Residence.jpg")
    Residence = models.ForeignKey(
        Residence, related_name="R_images", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Residence Images"

class ResidenceReviews(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    Residence = models.ForeignKey(
        Residence, on_delete=models.SET_NULL, null=True, related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Residence Reviews"


    def __str__(self):
        return self.Residence.title

    def get_rating(self):
        return self.rating

class wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    Residence = models.ForeignKey(Residence, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "wishlists"

    def __str__(self):
        return self.Residence.title


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    mobile1 = models.CharField(max_length=300, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"

core/forms.py
# from django import forms
# from core.models import Residence


# class ResidenceForms(forms.ModelForm):

core/views.py
from django.shortcuts import render, get_list_or_404
from core.models import Residence, Category, Vendor, ResidenceImages
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from userauths.models import User

def index(request):
    Residences = Residence.objects.filter(Residence_status="published", featured=True).order_by("-id")
    total_residences = Residence.objects.count()
    user_count = User.objects.count()

    context = {
        "Residences":Residences,
        "total_residences": total_residences,
        'active_page': 'index',
        'user_count': user_count,

    }
    return render(request, 'core/index.html',context=context)


def residence_view(request):
    Residences = Residence.objects.filter(Residence_status="published").order_by("-id")
    categories = Category.objects.all()

    context = {
        "Residences":Residences,
        "categories":categories,
        'active_page': 'residence',
    
    }
    return render(request, 'core/residence.html', context = context)




def search_view(request):
    query = request.GET.get("q")

    Residences = Residence.objects.filter(address__icontains=query).order_by("-date")

    context = {
        "Residences": Residences,
        "query": query,
    }
    return render(request, 'core/search.html', context)


def residence_detail_view(request, Rid):
    residence = Residence.objects.get(Rid=Rid)
    R_image = residence.R_images.all()

    context = {
        "R": residence,
        "R_image": R_image,
    }

    return render(request, "core/residence_detail.html", context)



def my_listings_view(request):
    # Filter residences based on the logged-in user
    residence = Residence.objects.filter(user=request.user)
    
    context = {
        "residence": residence,
        'active_page': 'my_listing',
    }
    return render(request, 'core/my_listing.html', context=context)

def filter_residence(request):
    Categories = request.GET.getlist('Category[]')
    minimum = request.GET.get('minimum')
    maximum = request.GET.get('maximum')

    residences = Residence.objects.filter(Residence_status="published").order_by("-id").distinct()

    if(minimum):
        residences = residences.filter(price__gt=minimum).distinct()
    if(maximum):
        residences = residences.filter(price__lt=maximum).distinct()
    if len(Categories) > 0:
        residences = residences.filter(category__id__in=Categories).distinct()

    
    data = render_to_string("core/async/residence.html", {"Residences": residences})
    return JsonResponse({"data": data})
    

def profile_view(request):
    return render(request, 'core/profile.html')

templates/core/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== FAVICON ===============-->
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.png' %}" type="image/x-icon">

    <!--=============== BOXICONS ===============-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    

    <!--=============== SWIPER CSS ===============-->
    <link rel="stylesheet" href="{% static 'assets/css/swiper-bundle.min.css' %}">

    <!-- Add these CDN links in the head section -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    
    
    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


        <title>FYP Home</title>
        <style>
            .alert{
                position: fixed;
                top: 60px;
                left: 25px;
                width: 100%;
                z-index: 1000;
            }
        </style>
</head>
<body>
    <header class="header" id="header">
        <nav class="nav container">
            <a href="#" class="nav__logo">
                FYP home <i class='bx bx-home' ></i>
            </a>
            <div class="nav__menu">
                <ul class="nav__list">
                    <li class="nav__item">
                        <a href="{% url 'core:index' %}" class="nav__link {% if active_page == 'index' %}active-link{% endif %}">
                            <i class='bx bx-home-alt-2' ></i>
                            <span>Home</span>
                        </a>
                    </li>

                    <li class="nav__item">
                            <a href="{% url 'core:residence' %}" class="nav__link {% if active_page == 'residence' %}active-link{% endif %}">
                                <i class='bx bx-award'></i>
                            <span>Residences</span>
                        </a>
                    </li>

                    <li class="nav__item">
                        <a href="{% url 'core:my_listing' %}" class="nav__link {% if active_page == 'my_listing' %}active-link{% endif %}">
                            <i class='bx bx-building-house' ></i>
                            <span>My Listing</span>
                        </a>
                    </li>
                   
                    <li class="nav__item">
                        <a href="{% url 'core:profile' %}" class="nav__link {% if active_page == 'profile' %}active-link{% endif %}">
                            <i class='bx bx-user-circle'></i>
                            <span>Profile</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!--theme change button  -->
            <i class='bx bx-moon change-theme' id="theme-button"></i>
        </nav>
</header>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
    <script>
        $(document).ready(function(){
            setTimeout(function(){
                $('.alert').fadeOut('slow');
            }, 3000); // 3000 milliseconds = 3 seconds
        });
    </script>
{% endif %}


<!--==================== VALUE ====================-->
<section class="value section" id="value">
    <div class="value__container container grid">
            <div class="value__content">

                {{user.username}}
                {{user.email}}
             <div>
                {% if request.user.is_authenticated %}
                <a href="{% url 'userauths:sign-out' %}" class="button register__button">
                    Sign Out
                </a>
                {% else %}
                <a href="{% url 'userauths:sign-in' %}" class="button register__button">
                    Sign Up
                </a>
                {% endif %}
            </div>
            </div>
</section>


    <footer class="footer section">
        <div class="footer__container container grid">
            <div>
                <a href="" class="footer__logo">
                    FYP home <i class='bx bx-home' ></i>
                </a>
                <p class="footer description">
                    our vision is to make all student<br>
                    the best place to live
                </p>
            </div>
    
            <div class="footer__content">
                <!-- 1 -->
                <div>
                    <h3 class="footer__title">
                        About
                    </h3>
    
                    <ul class="footer__links">
                        <li>
                            <a href="" class="footer_link">About Us</a>
                        </li>
                        <li>
                            <a href="" class="footer_link">Features</a>
                        </li>
                        <li>
                            <a href="" class="footer_link">News & Blogs</a>
                        </li>
                    </ul>
                </div>
                <!-- 2 -->
                <div>
                    <h3 class="footer__title">
                        Company
                    </h3>
    
                    <ul class="footer__links">
                        <li>
                            <a href="" class="footer_link">How we work?</a>
                        </li>
                        <li>
                            <a href="" class="footer_link">Capital</a>
                        </li>
                        <li>
                            <a href="" class="footer_link">Security</a>
                        </li>
                    </ul>
                </div>
                <!-- 3 -->
                <div>
                    <h3 class="footer__title">
                        Support
                    </h3>
    
                    <ul class="footer__links">
                        <li>
                            <a href="" class="footer_link">FAQs</a>
                        </li>
                        <li>
                            <a href="" class="footer_link">Support center</a>
                        </li>
                        <li>
                            <a href="" class="footer_link">Contact Us</a>
                        </li>
                    </ul>
                </div>
                <!-- 4 -->
                <div>
                    <h3 class="footer__title">
                        Follow Us
                    </h3>
    
                    <ul class="footer__social">
                        <a href="" class="footer__social-link">
                           <i class='bx bxl-facebook-circle'></i>
                        </a>
                        <a href="" class="footer__social-link">
                            <i class='bx bxl-instagram-alt'></i>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer__info container">
            <span class="footer__copy">
                &#169; FYP Home. All right reserved
            </span>
    
            <div class="footer__privacy">
                <a href="">Terms & Agreement</a>
                <a href="">Privacy Policy</a>
            </div>
        </div>
    </footer>
    
    
    <!--========== SCROLL UP ==========-->
     <a href="#" class="scrollup" id="scroll-up">
        <i class='bx bx-chevrons-up'></i>
     </a>
     <!--=============== SCROLLREVEAL ===============-->
     <script src="{% static 'assets/js/scrollreveal.min.js' %}"></script>
     
     <!--=============== SWIPER JS ===============-->
     <script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>
     
     <!--=============== MAIN JS ===============-->
     <script src="{% static 'assets/js/main.js' %}"></script>
     <script src="{% static 'assets/js/function.js' %}"></script>
    
    </body>
    </html>