FypProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

core/urls.py
from django import views
from django.urls import path
from core.views import index, residence_view, search_view, residence_detail_view, my_listings_view, filter_residence, profile_view

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("residences/", residence_view, name="residence"),
    path("profile/", profile_view, name="profile"),
    path("my_listing/", my_listings_view, name="my_listing"),
    path("residence/<str:Rid>", residence_detail_view, name="residence_detail"),

    # search
    path("search/", search_view, name="search"),

    path("filter-residences/", filter_residence, name="filter-residences"),

]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'home__search-input', 'placeholder': 'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'home__search-input', 'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'home__search-input', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'home__search-input', 'placeholder': 'Confirm Password'}))

    error_messages = {
        'password_mismatch': "The passwords do not match.",
        'unique_email': "An account with this email already exists.",
    }

    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User


# User = settings.AUTH_USER_MODEL


def register_view(request):
    
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, You account was created successfully.")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect("core:index")
    else:
        form = UserRegisterForm()


    context = {
        'form': form,
    }
    return render(request, "userauths/sign-up.html", context)



def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")
                return redirect("core:index")
            else:
                messages.warning(request, "User Does Not Exist, create an account.")
    
        except:
            messages.warning(request, f"User with {email} does not exist")
        
    
    return render(request, "userauths/sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request, "You logged out!")

    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% extends "partials/base.html" %}
{% load static %}
{% block main %}    
<section class="value section" id="value">
    <div class="value__container container grid">
        <div class="value__images">
            <div class="value__orbe"></div>

                <div class="value__img">
                    <img src={% static "assets/img/value.jpg" %} alt="">
                </div>
            </div> 
            <div class="value__content">
                <div class="value__data">
                    <h2 class="section__title">
                        Sign-In
                    </h2>
                    <a class="text-muted" href="{% url 'userauths:sign-up' %}" >Don't have an account?</a>
                </div><br>
                <form method="POST"> 
                    {% csrf_token %}

                    <div class="home__search">
                        <input type="text" required name="email" placeholder="Email *" class="home__search-input"/>
                    </div>
                    <div class="home__search">
                        <input required type="password" name="password" placeholder="Your password *" class="home__search-input"/>
                    </div>
                    <!-- <div class="login_footer form-group">
                        <div class="chek-form">
                            <input type="text" required="" name="email" placeholder="Security code *" />
                        </div>
                        <span class="security-code">
                            <b class="text-new">8</b>
                            <b class="text-hot">6</b>
                            <b class="text-sale">7</b>
                            <b class="text-best">5</b>
                        </span>
                    </div> -->
                    <div class="login_footer form-group mb-50">
                        <div class="chek-form">
                            <div class="custome-checkbox">
                                <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                            </div>
                        </div>
                        <a class="text-muted" href="#">Forgot password?</a>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="button register__button" name="login">Log in</button>
                    </div>
                </form>
            </div>
        </div>
</section>
{% endblock main %}

templates/userauths/sign-up.html
{% extends "partials/base.html" %}
{% load static %}
{% block main %}     
<section class="value section" id="value">
    <div class="value__container container grid">
        <div class="value__images">
            <div class="value__orbe"></div>

                <div class="value__img">
                    <img src={% static "assets/img/value.jpg" %} alt="">
                </div>
            </div> 
            <div class="value__content">
                
                <div class="value__data">
                    <h2 class="section__title">
                        Sign Up
                    </h2>
                {% if form.errors %}
                <div class="section__subtitle alert-danger">
                    <strong>{{form.errors}}</strong>
                </div>
                {% endif %}


                    <a class="text-muted" href="{% url 'userauths:sign-in' %}" >Allready have account!</a>
                </div><br>
                <form method="post" method="POST">
                    {% csrf_token %}
                    <div class="home__search">
                        {{form.username}}
                    </div>
                    <div class="home__search">
                        {{form.email}}
                    </div>
                    <div class="home__search">
                        {{form.password1}}
                    </div>
                    <div class="home__search">
                        {{form.password2}}
                    </div><br>
                        <button type="submit" class="button register__button"  name="login">Register</button>
                </form>
            </div>
        </div>
</section>


{% endblock main %}